apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ai-investment-dev
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: ai-investment-registry
    host: 0.0.0.0
    hostPort: "5001"
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
