package com.aiinvestment.portfolio.application;
import com.aiinvestment.portfolio.infrastructure.persistence.*; import org.apache.commons.csv.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.io.*; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*;
@Service public class Nifty500ReferenceService {
 static final String URL="https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv"; @org.springframework.beans.factory.annotation.Value("${market.nifty500.url:"+URL+"}") private String sourceUrl=URL; private final NseOfficialSecurityMaster nse; private final InstrumentMasterService masters; private final Nifty500UniverseRepository cache; private final NiftyIndustrySectorClassifier classifier; private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();
 public Nifty500ReferenceService(NseOfficialSecurityMaster nse,InstrumentMasterService masters,Nifty500UniverseRepository cache,NiftyIndustrySectorClassifier classifier){this.nse=nse;this.masters=masters;this.cache=cache;this.classifier=classifier;}
 @Transactional public Counts refresh(){ List<NseOfficialSecurityMaster.Listing> listings=nse.listedEquities(); if(listings.isEmpty())throw new IllegalStateException("NSE_MASTER_UNAVAILABLE"); List<Row> rows=fetch(); JoinResult joined=join(rows,listings); List<Nifty500UniverseEntity> next=new ArrayList<>();int canonicalized=0,unresolved=joined.unresolved();
  int mapped=0;Set<String> unmapped=new TreeSet<>();for(Joined r:joined.rows())try{var m=masters.canonicalizeOfficialNse(r.listing().isin(),r.nifty().symbol(),r.nifty().company());String sector=classifier.classify(r.nifty().industry());if(sector==null)unmapped.add(r.nifty().industry());else mapped++;next.add(new Nifty500UniverseEntity(m.getInstrumentId(),r.nifty().symbol(),r.listing().isin(),r.nifty().company(),r.nifty().industry(),sector,Instant.now()));canonicalized++;}catch(Exception e){unresolved++;}
  if(next.isEmpty())throw new IllegalStateException("NIFTY500_NO_JOINED_ROWS"); cache.deleteAllInBatch();cache.saveAll(next);return new Counts(rows.size(),rows.size(),joined.byIsin(),joined.bySymbol(),joined.mismatch(),unresolved,canonicalized,next.size(),mapped,next.size()-mapped,List.copyOf(unmapped)); }
 List<Row> fetch(){try{var req=HttpRequest.newBuilder(URI.create(sourceUrl)).timeout(Duration.ofSeconds(15)).header("User-Agent","Mozilla/5.0").GET().build();var res=http.send(req,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(res.statusCode()!=200)throw new IllegalStateException("NIFTY500_HTTP");return parse(res.body());}catch(Exception e){throw new IllegalStateException("NIFTY500_UNAVAILABLE",e);}}
 static List<Row> parse(String csv)throws Exception{List<Row> out=new ArrayList<>();Set<String> seen=new HashSet<>();try(CSVParser p=CSVFormat.DEFAULT.builder().setHeader().setSkipHeaderRecord(true).setTrim(true).build().parse(new StringReader(csv))){if(!p.getHeaderMap().keySet().containsAll(Set.of("Company Name","Industry","Symbol","ISIN Code")))throw new IllegalArgumentException("NIFTY500_REQUIRED_HEADERS_MISSING");for(CSVRecord r:p){String isin=InstrumentMasterEntity.normalizeIsin(v(r,"ISIN Code")),symbol=v(r,"Symbol"),industry=v(r,"Industry"),series=v(r,"Series");if(series!=null&&!"EQ".equalsIgnoreCase(series))continue;String key=isin!=null?"I:"+isin:"S:"+upper(symbol)+":"+upper(series);if(symbol!=null&&industry!=null&&seen.add(key))out.add(new Row(symbol,v(r,"Company Name"),isin,series,industry));}}return out;}
 static JoinResult join(List<Row> rows,List<NseOfficialSecurityMaster.Listing> listings){Map<String,NseOfficialSecurityMaster.Listing> byIsin=new HashMap<>();Map<String,List<NseOfficialSecurityMaster.Listing>> bySymbol=new HashMap<>();for(var l:listings){if(!"EQ".equalsIgnoreCase(l.series()))continue;if(l.isin()!=null)byIsin.put(l.isin(),l);bySymbol.computeIfAbsent(upper(l.symbol())+":"+upper(l.series()),k->new ArrayList<>()).add(l);}List<Joined> accepted=new ArrayList<>();int isins=0,symbols=0,mismatch=0,unresolved=0;for(Row r:rows){if(r.isin()!=null){var l=byIsin.get(r.isin());if(l==null){unresolved++;continue;}if(!l.symbol().equalsIgnoreCase(r.symbol())){mismatch++;continue;}accepted.add(new Joined(r,l));isins++;continue;}var choices=bySymbol.getOrDefault(upper(r.symbol())+":"+upper(r.series()),List.of());if(choices.size()!=1){unresolved++;continue;}accepted.add(new Joined(r,choices.get(0)));symbols++;}return new JoinResult(accepted,isins,symbols,mismatch,unresolved);}
 static String upper(String v){return v==null?"":v.trim().toUpperCase(Locale.ROOT);} static String v(CSVRecord r,String h){return r.isMapped(h)&&!r.get(h).isBlank()?r.get(h).trim():null;} public record Row(String symbol,String company,String isin,String series,String industry){} record Joined(Row nifty,NseOfficialSecurityMaster.Listing listing){} record JoinResult(List<Joined> rows,int byIsin,int bySymbol,int mismatch,int unresolved){} public record Counts(int fetchedNiftyRows,int parsedRows,int joinedByIsin,int joinedBySymbolFallback,int identityMismatch,int unresolved,int canonicalized,int activeUniverse,int sectorMapped,int sectorUnmapped,List<String> unmappedIndustries){}
}
