spring:
  application:
    name: risk-service
server:
  port: ${SERVER_PORT:8087}
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    console: "timestamp=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC} service=${spring.application.name} environment=${AIP_ENVIRONMENT:LOCAL} level=%p requestId=%X{correlationId:-} logger=%logger{36} message=%replace(%msg){'[\\r\\n]',' '}%n"
