package com.aiinvestment.portfolio.application;
import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*; import org.junit.jupiter.api.Test;
class Nifty500ReferenceServiceTest {
 @Test void parses_official_headers_deduplicates_isin_and_preserves_industry() throws Exception {var rows=Nifty500ReferenceService.parse("Company Name,Industry,Symbol,Series,ISIN Code\nAlpha,Financial Services,ALPHA,EQ,INE123A01016\nDuplicate,Financial Services,ALPHA2,EQ,INE123A01016\n");assertThat(rows).hasSize(1);assertThat(rows.get(0).industry()).isEqualTo("Financial Services");}
 @Test void rejects_changed_required_headers_and_malformed_or_non_equity_rows() throws Exception {assertThatThrownBy(()->Nifty500ReferenceService.parse("Company Name,Symbol\nAlpha,A\n")).isInstanceOf(IllegalArgumentException.class);assertThat(Nifty500ReferenceService.parse("Company Name,Industry,Symbol,Series,ISIN Code\nDebt,Financial Services,DEBT,N1,INE123A01016\n")).isEmpty();}
 @Test void joins_exact_isin_only_when_symbol_agrees() {var rows=java.util.List.of(new Nifty500ReferenceService.Row("ALPHA","Alpha","INE123A01016","EQ","Financial Services"));var master=java.util.List.of(new NseOfficialSecurityMaster.Listing("ALPHA","INE123A01016","Different Name","EQ"));var result=Nifty500ReferenceService.join(rows,master);assertThat(result.byIsin()).isEqualTo(1);assertThat(result.rows()).hasSize(1);}
 @Test void rejects_isin_symbol_disagreement_without_name_fallback() {var rows=java.util.List.of(new Nifty500ReferenceService.Row("WRONG","Same Company","INE123A01016","EQ","Financial Services"));var master=java.util.List.of(new NseOfficialSecurityMaster.Listing("RIGHT","INE123A01016","Same Company","EQ"));var result=Nifty500ReferenceService.join(rows,master);assertThat(result.mismatch()).isEqualTo(1);assertThat(result.rows()).isEmpty();}
 @Test void symbol_fallback_requires_unique_exact_symbol_and_series() {var row=new Nifty500ReferenceService.Row("ALPHA","Alpha",null,"EQ","Financial Services");var one=Nifty500ReferenceService.join(java.util.List.of(row),java.util.List.of(new NseOfficialSecurityMaster.Listing("ALPHA","INE123A01016","Alpha","EQ")));assertThat(one.bySymbol()).isEqualTo(1);var ambiguous=Nifty500ReferenceService.join(java.util.List.of(row),java.util.List.of(new NseOfficialSecurityMaster.Listing("ALPHA","INE123A01016","Alpha","EQ"),new NseOfficialSecurityMaster.Listing("ALPHA","INE999A01015","Alpha Two","EQ")));assertThat(ambiguous.rows()).isEmpty();assertThat(ambiguous.unresolved()).isEqualTo(1);}
 @Test void failed_master_fetch_never_touches_last_known_good_cache(){var nse=mock(NseOfficialSecurityMaster.class);var masters=mock(InstrumentMasterService.class);var cache=mock(com.aiinvestment.portfolio.infrastructure.persistence.Nifty500UniverseRepository.class);when(nse.listedEquities()).thenReturn(java.util.List.of());assertThatThrownBy(()->new Nifty500ReferenceService(nse,masters,cache,new NiftyIndustrySectorClassifier()).refresh()).isInstanceOf(IllegalStateException.class);verifyNoInteractions(cache);}
}
