package com.aiinvestment.multiparttest;

import com.aiinvestment.apigateway.ApiGatewayApplication;
import com.aiinvestment.shared.web.auth.HmacJwtService;
import com.aiinvestment.shared.web.auth.JwtClaims;
import jakarta.servlet.http.HttpServletRequest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.context.WebServerApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Runtime defect closure (Defect A, clipboard-paste PNG upload corruption).
 *
 * The real browser upload failure traced back to
 * {@code PortfolioRouteController.routeResearch} calling the String-based
 * {@code forward()}, which reads the raw multipart request body via
 * {@code StreamUtils.copyToString(..., StandardCharsets.UTF_8)}. A binary PNG
 * part is not valid UTF-8 text, so that decode (and the subsequent re-encode
 * back to bytes when the String is sent onward) silently corrupts the file
 * bytes before research-engine's Pillow validation ever sees them --
 * independent of anything in the frontend or research-engine's own Python
 * code, both of which were traced and found byte-correct.
 *
 * This test proves the fix end-to-end over real HTTP, through the real
 * gateway routing used in production (/api/v1/research/**), using a real
 * PNG generated by {@link ImageIO} (not a mocked filename/MIME pair) whose
 * bytes include values that are not valid standalone UTF-8 continuation
 * bytes -- exactly the class of byte sequence the old UTF-8 string hop
 * would mangle.
 */
class ResearchMultipartByteIntegrityHttpIntegrationTest {
    private static final String ISSUER = "research-multipart-test";
    private static final String SECRET = "research-multipart-test-jwt-secret-32-chars";
    private static final byte[] PNG_SIGNATURE = {
            (byte) 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A
    };

    private static ConfigurableApplicationContext downstream;
    private static ConfigurableApplicationContext gateway;
    private static String downstreamBaseUrl;
    private static String gatewayBaseUrl;
    private static byte[] realPng;

    @BeforeAll
    static void startRealHttpServersAndRealPng() throws Exception {
        realPng = generateRealPng();
        // Sanity check on the fixture itself: a genuine PNG always starts
        // with this exact 8-byte signature.
        byte[] signature = new byte[8];
        System.arraycopy(realPng, 0, signature, 0, 8);
        assertThat(signature).isEqualTo(PNG_SIGNATURE);

        downstream = new SpringApplicationBuilder(DownstreamConfiguration.class)
                .web(WebApplicationType.SERVLET).run("--server.port=0", "--spring.servlet.multipart.enabled=true",
                        "--test.research-downstream=true");
        downstreamBaseUrl = baseUrl(downstream);
        gateway = new SpringApplicationBuilder(ApiGatewayApplication.class)
                .run("--server.port=0", "--research.engine.base-url=" + downstreamBaseUrl,
                        "--auth.issuer=" + ISSUER, "--auth.jwt-secret=" + SECRET,
                        "--spring.servlet.multipart.enabled=false");
        gatewayBaseUrl = baseUrl(gateway);
    }

    @AfterAll
    static void stopRealHttpServers() {
        if (gateway != null) gateway.close();
        if (downstream != null) downstream.close();
    }

    @Test
    void directDownstreamReceivesTheExactPngSignatureAndBytes() throws Exception {
        Map<String, Object> result = sendRealPng(downstreamBaseUrl, false);
        assertPngBytesPreserved(result);
    }

    @Test
    void gatewayRouteResearchPreservesExactPngBytesThroughTheProxy() throws Exception {
        // Reproduces the real browser request shape: POST to
        // /api/v1/research/evidence/draft with multipart/form-data carrying
        // a "file" part, through the actual gateway route that previously
        // corrupted it.
        Map<String, Object> result = sendRealPng(gatewayBaseUrl, true);
        assertPngBytesPreserved(result);
    }

    private void assertPngBytesPreserved(Map<String, Object> result) throws Exception {
        assertThat((String) result.get("firstEightBytesHex"))
                .isEqualTo(HexFormat.of().formatHex(PNG_SIGNATURE));
        assertThat((Integer) result.get("size")).isEqualTo(realPng.length);
        assertThat((String) result.get("sha256")).isEqualTo(sha256Hex(realPng));
        assertThat((Boolean) result.get("pillowCompatible")).isTrue();
    }

    private static Map<String, Object> sendRealPng(String baseUrl, boolean authenticated) throws Exception {
        String boundary = "----AipRealPngMultipartBoundary9ZQ3";
        byte[] prefix = ("--" + boundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\""
                + "snip.png" + "\"\r\nContent-Type: image/png\r\n\r\n").getBytes(StandardCharsets.UTF_8);
        byte[] suffix = ("\r\n--" + boundary + "--\r\n").getBytes(StandardCharsets.UTF_8);
        byte[] body = new byte[prefix.length + realPng.length + suffix.length];
        System.arraycopy(prefix, 0, body, 0, prefix.length);
        System.arraycopy(realPng, 0, body, prefix.length, realPng.length);
        System.arraycopy(suffix, 0, body, prefix.length + realPng.length, suffix.length);

        HttpRequest.Builder request = HttpRequest.newBuilder()
                .uri(URI.create(baseUrl + "/api/v1/research/evidence/draft"
                        + "?global_instrument_id=f86f7c59-85a6-40f2-a643-481c3ec2f53a&evidence_type=SHAREHOLDING"))
                .header(HttpHeaders.CONTENT_TYPE, "multipart/form-data; boundary=" + boundary)
                .POST(HttpRequest.BodyPublishers.ofByteArray(body));
        if (authenticated) request.header(HttpHeaders.AUTHORIZATION, "Bearer " + token());
        HttpResponse<String> response = HttpClient.newHttpClient().send(
                request.build(), HttpResponse.BodyHandlers.ofString());
        assertThat(response.statusCode()).isEqualTo(200);
        return parseJsonObject(response.body());
    }

    private static byte[] generateRealPng() throws Exception {
        BufferedImage image = new BufferedImage(12, 12, BufferedImage.TYPE_INT_RGB);
        for (int x = 0; x < image.getWidth(); x++) {
            for (int y = 0; y < image.getHeight(); y++) {
                // Deliberately varied pixel values so the compressed PNG
                // stream contains byte values across the full 0-255 range,
                // including bytes that are not valid standalone UTF-8
                // continuation bytes on their own (e.g. 0x89 in the PNG
                // signature itself, and high-bit bytes in the compressed
                // IDAT stream) -- exactly what a naive UTF-8 string hop
                // would corrupt.
                int rgb = ((x * 23 + y * 61) % 256) << 16 | ((x * 97) % 256) << 8 | ((y * 131) % 256);
                image.setRGB(x, y, rgb);
            }
        }
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        boolean wrote = ImageIO.write(image, "png", out);
        assertThat(wrote).isTrue();
        return out.toByteArray();
    }

    private static String sha256Hex(byte[] data) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(data));
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> parseJsonObject(String json) throws Exception {
        return new com.fasterxml.jackson.databind.ObjectMapper().readValue(json, Map.class);
    }

    private static String token() {
        return new HmacJwtService(SECRET).issue(new JwtClaims(
                ISSUER, "user-a", null, null, List.of("USER"), Instant.now().plusSeconds(300)));
    }

    private static String baseUrl(ConfigurableApplicationContext context) {
        int port = ((WebServerApplicationContext) context).getWebServer().getPort();
        return "http://127.0.0.1:" + port;
    }

    @Configuration(proxyBeanMethods = false)
    @EnableAutoConfiguration
    @Import(ResearchDownstreamController.class)
    static class DownstreamConfiguration {}

    /**
     * Stands in for research-engine's real
     * POST /api/v1/research/evidence/draft endpoint for the purposes of this
     * byte-integrity test: it does not run the real Pillow/OCR pipeline (that
     * is covered separately by the Python backend multipart test using a
     * real FastAPI TestClient), it only reports exactly what bytes it
     * received so this test can prove the gateway hop is byte-exact. A
     * genuinely corrupted PNG (e.g. UTF-8-mangled) would fail the
     * signature/size/hash checks first -- the explicit "pillowCompatible"
     * flag mirrors the real backend's own first validation step
     * (Image.open(...).verify()) for completeness.
     */
    @RestController
    @ConditionalOnProperty(name = "test.research-downstream", havingValue = "true")
    static class ResearchDownstreamController {
        @PostMapping(value = "/api/v1/research/evidence/draft", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
        Map<String, Object> draft(@RequestPart("file") MultipartFile file, HttpServletRequest request)
                throws Exception {
            byte[] received = file.getBytes();
            byte[] firstEight = new byte[Math.min(8, received.length)];
            System.arraycopy(received, 0, firstEight, 0, firstEight.length);
            boolean pillowCompatible;
            try {
                pillowCompatible = ImageIO.read(new java.io.ByteArrayInputStream(received)) != null;
            } catch (Exception decodeFailure) {
                pillowCompatible = false;
            }
            return Map.of(
                    "size", received.length,
                    "firstEightBytesHex", HexFormat.of().formatHex(firstEight),
                    "sha256", sha256Hex(received),
                    "pillowCompatible", pillowCompatible,
                    "contentType", request.getContentType()
            );
        }
    }
}
