UPDATE watchlists
SET name = CASE region
    WHEN 'INDIA' THEN 'WATCHLIST-IND'
    WHEN 'USA' THEN 'WATCHLIST-USA'
    WHEN 'EUROPE' THEN 'WATCHLIST-EU'
END
WHERE system_default = TRUE
  AND name IN ('IND-WATCHLIST', 'USA-WATCHLIST', 'EU-WATCHLIST');
