package com.aiinvestment.auth;

import com.aiinvestment.shared.web.auth.HmacJwtService;
import com.aiinvestment.shared.web.auth.JwtClaims;
import jakarta.transaction.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;

@Service
public class AuthLifecycleService {
    private final AuthProperties properties; private final AppUserRepository users; private final EmailVerificationTokenRepository tokens; private final PasswordResetTokenRepository resets; private final AuthEmailSender emailSender;
    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder(12); private final SecureRandom random = new SecureRandom();
    public AuthLifecycleService(AuthProperties properties, AppUserRepository users, EmailVerificationTokenRepository tokens, PasswordResetTokenRepository resets, AuthEmailSender emailSender){this.properties=properties;this.users=users;this.tokens=tokens;this.resets=resets;this.emailSender=emailSender;}
    @Transactional public AuthController.RegistrationResponse register(AuthController.RegisterRequest request){String normalized=normalize(request.email());if(!isValidEmail(normalized))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid email address");Instant now=Instant.now();String displayName=(request.firstName().trim()+" "+request.lastName().trim()).trim();AppUserEntity user=users.findByNormalizedEmail(normalized).map(existing->{if("ACTIVE".equals(existing.getAccountStatus()))throw new ResponseStatusException(HttpStatus.CONFLICT,"An account already exists for this email. Sign in or reset your password.");if(!"EMAIL_VERIFICATION_PENDING".equals(existing.getAccountStatus()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Unable to register account");existing.refreshPendingRegistration(request.email().trim(),passwordEncoder.encode(request.password()),displayName,now);tokens.deleteByUserId(existing.getId());return existing;}).orElseGet(()->users.save(AppUserEntity.local(UUID.randomUUID(),properties.issuer(),request.email().trim(),normalized,passwordEncoder.encode(request.password()),displayName,now)));String raw=rawToken();tokens.save(new EmailVerificationTokenEntity(UUID.randomUUID(),user.getId(),hash(raw),now.plusSeconds(properties.verificationTokenTtlSeconds()),now));if(emailSender.isConfigured())emailSender.sendVerification(user.getId(),user.getEmail(),raw);return new AuthController.RegistrationResponse(user.getId(),"EMAIL_VERIFICATION_PENDING");}
    @Transactional public AuthController.VerificationResponse verify(String raw){Instant now=Instant.now();EmailVerificationTokenEntity token=tokens.findByTokenHash(hash(raw)).orElseThrow(()->invalidToken());if(token.getConsumedAt()!=null||!token.getExpiresAt().isAfter(now))throw invalidToken();AppUserEntity user=users.findById(token.getUserId()).orElseThrow(()->invalidToken());if("DISABLED".equals(user.getAccountStatus()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Account is disabled");token.consume(now);user.activate(now);return new AuthController.VerificationResponse(user.getId(),"ACTIVE");}
    @Transactional public AuthController.GenericEmailResponse resendVerification(String email){users.findByNormalizedEmail(normalize(email)).filter(user -> "EMAIL_VERIFICATION_PENDING".equals(user.getAccountStatus())).ifPresent(user -> {if(emailSender.isConfigured()){Instant now=Instant.now();tokens.deleteByUserId(user.getId());String raw=rawToken();tokens.save(new EmailVerificationTokenEntity(UUID.randomUUID(),user.getId(),hash(raw),now.plusSeconds(properties.verificationTokenTtlSeconds()),now));emailSender.sendVerification(user.getId(),user.getEmail(),raw);}});return new AuthController.GenericEmailResponse("If the account is eligible, a new verification email has been sent.");}
    @Transactional public AuthController.TokenResponse login(AuthController.LoginRequest request){AppUserEntity user=users.findByNormalizedEmail(normalize(request.email())).orElseThrow(()->badCredentials());if(user.getPasswordHash()==null||!passwordEncoder.matches(request.password(),user.getPasswordHash()))throw badCredentials();if(!"ACTIVE".equals(user.getAccountStatus()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Email verification is required");user.recordLogin(Instant.now());return issue(user,List.of("USER"));}
    @Transactional public AuthController.PasswordResetRequestResponse requestPasswordReset(String email){users.findByNormalizedEmail(normalize(email)).filter(user -> "ACTIVE".equals(user.getAccountStatus())).ifPresent(user -> { if(emailSender.isConfigured()){Instant now=Instant.now();String raw=rawToken();resets.save(new PasswordResetTokenEntity(UUID.randomUUID(),user.getId(),hash(raw),now.plusSeconds(properties.passwordResetTokenTtlSeconds()),now));emailSender.sendPasswordReset(user.getId(),user.getEmail(),raw);}});return new AuthController.PasswordResetRequestResponse("If an eligible account exists, reset instructions will be sent.");}
    @Transactional public void confirmPasswordReset(String raw,String newPassword){if(newPassword==null||newPassword.length()<12||newPassword.length()>200)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid password");Instant now=Instant.now();PasswordResetTokenEntity token=resets.findByTokenHash(hash(raw)).orElseThrow(()->invalidToken());if(token.getConsumedAt()!=null||!token.getExpiresAt().isAfter(now))throw invalidToken();AppUserEntity user=users.findById(token.getUserId()).orElseThrow(()->invalidToken());if(!"ACTIVE".equals(user.getAccountStatus()))throw invalidToken();user.resetPassword(passwordEncoder.encode(newPassword),now);token.consume(now);}
    public AuthController.TokenResponse issue(AppUserEntity user,List<String> roles){Instant now=Instant.now(),exp=now.plusSeconds(properties.tokenTtlSeconds());String jwt=new HmacJwtService(properties.jwtSecret()).issue(new JwtClaims(properties.issuer(),user.getExternalSubject(),user.getEmail(),user.getDisplayName(),roles,now,exp));return new AuthController.TokenResponse(jwt,"Bearer",exp,AuthController.UserResponse.from(user,roles));}
    private static String normalize(String email){return email.trim().toLowerCase(Locale.ROOT);} private static boolean isValidEmail(String email){return email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");} private String rawToken(){byte[] bytes=new byte[32];random.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);} private static String hash(String raw){try{return Base64.getUrlEncoder().withoutPadding().encodeToString(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private static ResponseStatusException invalidToken(){return new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid or expired verification token");} private static ResponseStatusException badCredentials(){return new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password");}
}
