spring:
  application:
    name: company-service
server:
  port: ${SERVER_PORT:8084}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
logging:
  pattern:
    level: "%5p [correlationId:%X{correlationId:-}]"
